name: glxgears-example
version: '0.1'
summary: glxgears example kiosk

description: |
  glxgears example X11 kiosk, using Xwayland and Wayland
base: core18
confinement: strict
grade: devel

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11

plugs:
  opengl:
  wayland:
  network-bind: # Needed (NOT the x11 slot) to serve X11  

parts:
  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [ build-essential ]
    stage-packages: [ xwayland, i3, libegl1-mesa, libgl1-mesa-glx ]
    
  glxgears:
    plugin: nil
    stage-packages:
      - mesa-utils

environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: title="glxgears"

apps:
  glxgears-example:
    command: xwayland-kiosk-launch glxgears

  daemon:
    command: xwayland-kiosk-launch glxgears
    daemon: simple
